version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnet
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build:
      context: ./aspnet-core
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ConnectionStrings__Default: "Server=sqlserver;Database=ProjectBankDb;User=sa;Password=Your_password123;"
      App__CorsOrigins: "http://frontend"
      App__ClientRootAddress: "http://frontend"
      App__ServerRootAddress: "http://backend"
    depends_on:
      - sqlserver
    ports:
      - "5000:80"
    networks:
      - appnet

  frontend:
    build:
      context: ./angular
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  sql_data:
